import os
import re
import json
import time
from pathlib import Path
from typing import List, Optional
from codesys_debug import CodesysCompiler, ResponseData, ErrorMessage
from library_recommender import recommend_library_snippets

# CODESYS API 配置 - 优先使用环境变量，否则使用默认值
CODESYS_API_URL = os.getenv("CODESYS_API_URL", "http://192.168.103.117:9000/api/v1/pou/project_workflow")

# 智增增API配置 - 必须从环境变量读取
ZHIZENGZENG_API_KEY = os.getenv("ZHIZENGZENG_API_KEY")
ZHIZENGZENG_BASE_URL = os.getenv("ZHIZENGZENG_BASE_URL", "https://api.zhizengzeng.com/v1")

#暂时冻结不用的prompt:
#- If you find  "END_FUNCTION" or "END_FUNCTION_BLOCK" in the end of the code, remove it.


# 从verifier_agent.py中提取的prompt模板（修改版：直接返回完整代码）
verifier_system_prompt = """
ROLE: 
You are an expert in Structured Text (ST) programming for IEC 61131-3-compliant PLCs using the Codesys development environment. 
You specialize in identifying and correcting syntax and semantic errors based on compiler feedback generated by Codesys.

GOALS: 
Generate the complete corrected code that is syntactically and semantically correct within the Codesys environment.

WORKFLOW:
1. Analyze the compiler error messages provided by the Codesys IDE and identify all erroneous parts in the ST code.
2. Understand why the errors occurred using IEC 61131-3 rules and Codesys-specific language semantics.
3. Generate the COMPLETE corrected code that fixes all identified errors.
4. Return the entire fixed code in the required format.

IMPORTANT:
- Assume compilation is performed within the Codesys environment.
- You must return the COMPLETE corrected code, not just patches.
- The returned code must be syntactically valid for Structured Text in Codesys.
- Clearly identify violated syntax rules, common function block misuse, or incorrect data typing.
- Consider that some compiler errors may cascade—reason about task execution flow and variable scope to identify the root issue.
- Preserve the original control logic and behavior as much as possible, only fix errors.
- If you find a "BEGIN" between the variable declarations and the code logic section, remove it.
- Do not use variables that are not declared in the declaration section.

==================== STRICT RULES ====================
1. DO NOT define or declare any new POU.
   This includes, but is not limited to:
   - FUNCTION
   - FUNCTION_BLOCK
   - PROGRAM

2. DO NOT add or modify any declaration sections.
   The following blocks MUST NOT be added or changed:
   - VAR
   - VAR_INPUT
   - VAR_OUTPUT
   - VAR_IN_OUT
   - VAR_TEMP
   - TYPE

3. DO NOT introduce any new variables, instances, types,
   function blocks, or functions.

4. You may ONLY modify executable statements
   in the implementation body.

5. If the code being fixed is a FUNCTION:
   - Use `RETURN;` to return.
   - DO NOT assign a value during RETURN.
   - NEVER use `RETURN(value);`.

6. Comments MUST strictly follow Structured Text syntax.
   When adding comments, prefix them with:
   // comment text

7. Preserve the code structure and formatting as much as possible.
   Only modify what is necessary to fix the errors.

8. If the compiler error CANNOT be fixed under these rules,
   output exactly:
   <UNFIXABLE>

OUTPUT FORMAT:
You MUST return the COMPLETE corrected code wrapped in the following XML tags:
```xml
<FixedCode>
[The complete corrected ST code here, including all declarations and implementation]
</FixedCode>
```

The code inside <FixedCode> tags should be the full, corrected version of the input code that fixes all compiler errors.

--Appendix--
ST Library Functions:
{api_details}
ST Programming Guidelines:
{programming_guidance}
"""

#user prompt

#old version:
#If it is not possible to ensure that all variables are declared, no new variables shall be added; repairs shall only be implemented by modifying existing variables/logic.
verifier_instance_prompt = """
If it is not possible to ensure that all variables are declared, no new variables shall be added; repairs shall only be implemented by modifying existing variables.

IMPORTANT: You must return the COMPLETE corrected code, not patches. The output should be the full, fixed version of the entire code.

Input structured in XML format:
<!-- Code with errors. -->
<STCode>
{st_code}
</STCode>
<!-- Errors. -->
<Errors>
{static_analysis_results}
</Errors>
<!-- Error information of the library function that caused the call failure. -->
<library_function_infos>
{function_infos}
</library_function_infos>

Please analyze the errors and return the COMPLETE corrected code wrapped in <FixedCode> tags.
"""

programming_guidance = "NO PROGRAMMING GUIDANCE"


def extract_content(response) -> str:
    """
    提取响应内容中的st代码。
    支持多种响应格式。
    """
    if hasattr(response, 'choices'):
        choice = response.choices[0]
        if hasattr(choice, 'message') and hasattr(choice.message, 'content'):
            st_code = choice.message.content
        else:
            st_code = choice['message']['content']
    elif hasattr(response, 'content'):
        st_code = response.content[0].text if isinstance(response.content, list) else response.content
    elif isinstance(response, str):
        st_code = response
    else:
        st_code = str(response)
    return st_code


def parse_fixed_code(text: str) -> Optional[str]:
    """
    解析给定文本中的修复后的完整代码。
    
    参数:
    - text: LLM返回的文本，应包含修复后的完整代码
    
    返回:
    - Optional[str]: 修复后的完整代码，如果解析失败或标记为不可修复则返回None
    
    解析策略:
    1. 优先提取 <FixedCode>...</FixedCode> 标签中的内容
    2. 如果没有找到，尝试提取 markdown 代码块
    3. 如果都没有，检查是否直接返回了代码（包含关键字）
    """
    # 首先检查是否有 <UNFIXABLE> 标记
    if "<UNFIXABLE>" in text.upper():
        return None
    
    # 尝试提取 <FixedCode> 标签中的内容
    pattern = re.compile(
        r'<FixedCode>(.*?)</FixedCode>', 
        re.DOTALL
    )
    
    matches = pattern.findall(text)
    
    if matches:
        # 返回第一个匹配的完整代码
        fixed_code = matches[0].strip()
        return fixed_code
    
    # 如果没有找到 <FixedCode> 标签，尝试提取代码块
    # 检查是否有 markdown 代码块
    code_block_pattern = re.compile(
        r'```(?:st|plaintext|text)?\s*\n(.*?)```',
        re.DOTALL
    )
    code_block_matches = code_block_pattern.findall(text)
    
    if code_block_matches:
        # 返回最后一个代码块（通常是完整的修复代码）
        fixed_code = code_block_matches[-1].strip()
        return fixed_code
    
    # 如果都没有找到，尝试返回整个文本（可能是直接返回的代码）
    # 但需要检查是否包含明显的代码结构
    if any(keyword in text for keyword in ['FUNCTION', 'FUNCTION_BLOCK', 'PROGRAM', 'VAR_INPUT', 'VAR_OUTPUT']):
        return text.strip()
    
    return None


def call_llm_for_fix(messages: List[dict], llm_client=None, use_openai: bool = False, 
                     openai_api_key: Optional[str] = None, model: str = "gpt-4o",
                     base_url: Optional[str] = None) -> str:
    """
    调用大模型进行代码修复。
    
    参数:
    - messages: 消息列表，格式为 [{"role": "system", "content": "..."}, ...]
    - llm_client: 自定义的LLM客户端对象，如果有则使用它
    - use_openai: 是否使用openai库（需要安装openai包）
    - openai_api_key: API密钥
    - model: 使用的模型名称
    - base_url: API的基础URL（用于智增增等API中转站），如果为None则使用OpenAI默认URL
    
    返回:
    - str: 模型返回的修复建议文本
    """
    if llm_client is not None:
        # 使用自定义客户端
        if hasattr(llm_client, 'call'):
            response = llm_client.call(messages=messages)
            return extract_content(response)
        elif hasattr(llm_client, '__call__'):
            response = llm_client(messages)
            return extract_content(response)
        else:
            raise ValueError("自定义LLM客户端必须实现call方法或可调用")
    
    if use_openai:
        try:
            import openai
            if base_url:
                # 使用自定义base_url（如智增增API）
                client = openai.OpenAI(
                    api_key=openai_api_key,
                    base_url=base_url
                )
            elif openai_api_key:
                # 使用OpenAI官方API
                client = openai.OpenAI(api_key=openai_api_key)
            else:
                # 尝试从环境变量获取
                client = openai.OpenAI()
            
            response = client.chat.completions.create(
                model=model,
                messages=messages
            )
            return extract_content(response)
        except ImportError:
            raise ImportError("需要安装openai库: pip install openai")
        except Exception as e:
            raise Exception(f"调用API失败: {e}")
    
    # 如果没有提供客户端，返回提示信息
    raise ValueError("请提供llm_client参数或设置use_openai=True并配置openai_api_key")


def auto_fix_st_code(
    st_file_path: str,
    project_name: str,
    block_name: Optional[str] = None,
    max_verify_count: int = 3,
    ip_port: Optional[str] = None,
    llm_client=None,
    use_openai: bool = False,
    openai_api_key: Optional[str] = None,
    model: str = "gpt-4o",
    base_url: Optional[str] = None,
    api_details: str = "",
    programming_guidance_text: Optional[str] = None,
    version_save_dir: Optional[str] = None
) -> tuple:
    """
    自动修复ST代码的主流程。
    
    参数:
    - st_file_path: test.st文件的路径
    - block_name: 代码块名称，如果为None则从文件内容中提取
    - max_verify_count: 最大验证/修复次数
    - ip_port: CODESYS API地址，如果为None则使用默认值
    - llm_client: 自定义的LLM客户端对象
    - use_openai: 是否使用openai库
    - openai_api_key: API密钥
    - model: 使用的模型名称
    - base_url: API的基础URL（用于智增增等API中转站），如果为None则使用OpenAI默认URL
    - api_details: ST库函数详情（用于system prompt）
    - programming_guidance_text: 编程指导文本（用于system prompt）
    
    返回:
    - tuple: (修复后的代码, 是否成功, 尝试次数)

    额外:
    - 若提供 version_save_dir，则会在该目录下按“文件名_序号.st”保存每次修改后的版本，
      0 表示初始代码，序号与修复轮次一致。
    """
    # 读取test.st文件
    if not os.path.exists(st_file_path):
        raise FileNotFoundError(f"文件不存在: {st_file_path}")
    
    with open(st_file_path, 'r', encoding='utf-8') as f:
        st_code = f.read()
    
    # 如果没有指定block_name，尝试从代码中提取
    if block_name is None:
        # 尝试提取FUNCTION_BLOCK或PROGRAM名称
        match = re.search(r'(?:FUNCTION_BLOCK|PROGRAM|FUNCTION)\s+(\w+)', st_code, re.IGNORECASE)
        if match:
            block_name = match.group(1)
        else:
            block_name = "TestBlock"
    
    # 版本快照保存
    base_filename = os.path.splitext(os.path.basename(st_file_path))[0]
    if version_save_dir:
        os.makedirs(version_save_dir, exist_ok=True)
        def _save_version(code_str: str, suffix: int):
            file_path = os.path.join(version_save_dir, f"{base_filename}_{suffix}.st")
            with open(file_path, 'w', encoding='utf-8') as vf:
                vf.write(code_str)
            print(f"  [版本快照] 已保存: {file_path}")
        _save_version(st_code, 0)  # 保存初始版本
    else:
        def _save_version(code_str: str, suffix: int):
            return

    # 使用默认IP地址
    if ip_port is None:
        ip_port = CODESYS_API_URL
    
    # 初始化编译器实例
    compiler = CodesysCompiler()
    start_time = time.time()
    
    # 构建验证器的系统提示信息
    pg_text = programming_guidance_text if programming_guidance_text is not None else programming_guidance
    verifier_system_prompt_with_data = verifier_system_prompt.format(
        api_details=api_details,
        programming_guidance=pg_text
    )
    
    verifier_messages = [{"role": "system", "content": verifier_system_prompt_with_data}]
    
    # 尝试验证和修复代码，直到成功或达到最大尝试次数
    verify_count = 0
    while verify_count < max_verify_count:
        verify_count += 1
        print(f"\n{'='*60}")
        print(f"第 {verify_count} 次验证尝试")
        print(f"{'='*60}")
        
        # 调用语法检查
        check_result = compiler.syntax_check(project_name, block_name, st_code, ip_port)

        no_error = check_result.success
        
        elapsed_time = time.time() - start_time
        print(f"编译耗时: {elapsed_time:.2f} 秒")
        
        if no_error:
            print(f"{block_name} SUCCESS!")
            # print(f"\n最终代码:\n{st_code}")
            return (st_code, True, verify_count)
        else:
            error_list = []
            
            # 首选 Declaration Section 的错误，因为会引发级联错误
            for error in check_result.errors:
                if error.error_type == "Declaration Section Error":
                    print(f"Declaration Error >>> {str(error)}")
                    error_list.append(error.to_dict())
            
            # 如果没有 Declaration Section 的错误，则检查 Implementation Section 的错误
            if not error_list:
                for error in check_result.errors:
                    if error.error_type == "Implementation Section Error":
                        # print(f'Implementation Error >>>> {str(error)}')
                        error_list.append(error.to_dict())
            
            # 记录所有错误信息
            all_errors = [error.to_dict() for error in check_result.errors]
            error_log = '\n'.join([str(err) for err in error_list])

            # 基于报错推荐相关库函数信息（名称 + 对应 infos 文件标识）
            # 传入 all_errors（字典列表）而不是 error_log（字符串），以便提取 line_content
            lib_snippets = recommend_library_snippets(all_errors)
            if lib_snippets:
                # 目前先以简单 JSON 形式提供给大模型，后续可根据需要调整格式
                function_infos = json.dumps(
                    [{"name": name, "info": info} for name, info in lib_snippets],
                    ensure_ascii=False,
                    indent=2,
                )
            else:
                function_infos = ""
            
            # 准备本轮日志落盘位置（与历史版本同级 logs 目录）
            log_path = None
            log_lines = []
            if version_save_dir:
                logs_dir = Path(version_save_dir).resolve().parent / "logs"
                logs_dir.mkdir(parents=True, exist_ok=True)
                log_path = logs_dir / f"{Path(st_file_path).stem}_round{verify_count}.log"
                log_lines.append(f"[Round {verify_count}] block={block_name}")
                log_lines.append(f"errors_count={len(check_result.errors)}")
                log_lines.append("errors:")
                log_lines.append(error_log if error_log else "(none)")
                log_lines.append("")
            
            print(f'\n{block_name} 发现错误，开始调用大模型修复...')
            print(f"错误总数: {len(check_result.errors)}")
            
            # 构建用户提示
            verifier_instance_prompt_with_data = verifier_instance_prompt.format(
                static_analysis_results=error_log,
                st_code=st_code,
                function_infos=function_infos
            )

            print(f"错误调用函数信息:\n {function_infos}")

            verifier_messages.append({"role": "user", "content": verifier_instance_prompt_with_data})
            
            # 使用AI模型生成修复补丁
            try:
                verify_result = call_llm_for_fix(
                    verifier_messages,
                    llm_client=llm_client,
                    use_openai=use_openai,
                    openai_api_key=openai_api_key,
                    model=model,
                    base_url=base_url
                )
                
                verifier_messages.append({"role": "assistant", "content": verify_result})
                print(f"\n模型返回的修复代码:\n{verify_result[:500]}...\n")
                if log_path:
                    log_lines.append("llm_response:")
                    log_lines.append(verify_result)
                    log_lines.append("")
                
                # 解析修复后的完整代码
                fixed_code = parse_fixed_code(verify_result)
                
                if not fixed_code:
                    if "<UNFIXABLE>" in verify_result.upper():
                        print("警告: 模型标记为不可修复，跳过本次修复")
                    else:
                        print("警告: 未能从模型响应中解析出修复后的代码，跳过本次修复")
                    if log_path:
                        log_lines.append("parse_fixed_code: failed to parse")
                        log_path.write_text("\n".join(log_lines), encoding="utf-8")
                    continue
                
                # 直接用修复后的完整代码替换原代码
                print(f"应用修复后的完整代码...")
                old_code = st_code
                st_code = fixed_code
                
                # 验证代码结构是否保持（至少应该包含相同的POU声明）
                old_pou_match = re.search(r'(?:FUNCTION_BLOCK|PROGRAM|FUNCTION)\s+(\w+)', old_code, re.IGNORECASE)
                new_pou_match = re.search(r'(?:FUNCTION_BLOCK|PROGRAM|FUNCTION)\s+(\w+)', st_code, re.IGNORECASE)
                
                if old_pou_match and new_pou_match:
                    if old_pou_match.group(1) != new_pou_match.group(1):
                        print(f"  ⚠️  警告: POU名称不匹配，可能代码结构发生变化")
                
                print(f"  ✓ 已应用修复后的完整代码")
                
                # 保存本轮修复后的版本
                _save_version(st_code, verify_count)
                if log_path:
                    log_lines.append("code_replacement: applied complete fixed code")
                    log_path.write_text("\n".join(log_lines), encoding="utf-8")
                
            except Exception as e:
                print(f"调用大模型失败: {e}")
                if log_path:
                    log_lines.append(f"exception: {e}")
                    log_path.write_text("\n".join(log_lines), encoding="utf-8")
                print("跳过本次修复尝试")
                continue
            
            print(f"{block_name} 修复完成 ({verify_count}/{max_verify_count}) - 执行时间: {(time.time() - start_time):.6f} 秒")
    
    # 达到最大尝试次数仍未成功
    print(f"\n{'='*60}")
    print(f"达到最大尝试次数 ({max_verify_count})，停止修复")
    print(f"{'='*60}")
    return (st_code, False, verify_count)


if __name__ == "__main__":
    # 测试代码
    test_st_path = os.path.join(os.path.dirname(__file__), "test.st")
    
    print("=" * 60)
    print("开始自动修复ST代码流程")
    print("=" * 60)
    print(f"读取文件: {test_st_path}")
    
    # 智增增API配置 - 从环境变量读取
    API_KEY = ZHIZENGZENG_API_KEY
    BASE_URL = ZHIZENGZENG_BASE_URL
    
    # 检查API配置
    if not API_KEY or API_KEY == "":
        print("错误: 未配置API密钥！")
        print("请在CMD中设置环境变量:")
        print("  set ZHIZENGZENG_API_KEY=你的API密钥")
        print("  set ZHIZENGZENG_BASE_URL=https://api.zhizengzeng.com/v1")
        exit(1)
    
    print(f"使用API地址: {BASE_URL}")
    print(f"使用模型: gpt-4o")
    
    # 使用智增增API进行自动修复
    fixed_code, success, count = auto_fix_st_code(
        test_st_path,
        max_verify_count=3,
        use_openai=True,
        openai_api_key=API_KEY,
        base_url=BASE_URL,
        model="gpt-4o"  # 可以根据智增增支持的模型调整
    )
    
    if success:
        print(f"\n✓ 修复成功！共尝试 {count} 次")
        # 可选：保存修复后的代码
        output_path = os.path.join(os.path.dirname(__file__), "test_fixed.st")
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(fixed_code)
        print(f"修复后的代码已保存到: {output_path}")
    else:
        print(f"\n✗ 修复失败，已达到最大尝试次数 ({count})")

